clear secrets before setting secrets + better printing

diff --git a/set_secrets_from_dev_vars b/set_secrets_from_dev_vars
--- a/set_secrets_from_dev_vars
+++ b/set_secrets_from_dev_vars
@@ -7,14 +7,35 @@ if ! [ -f ".dev.vars" ]; then
 	exit 1
 fi
 
+# clean up secrets from CF and GH
+secret_list=$(yarn wrangler secret list | grep "name" || true)
+if [ -n "$secret_list" ]; then
+	echo "# Clearing secrets"
+	awk '{gsub(/[",]/, ""); print $2}' <<<"$secret_list" |
+	while read -rs ENV; do
+		echo "- $ENV"
+		yarn wrangler secret delete "$ENV" &> /dev/null
+		if command -v gh 1> /dev/null && [[ -n "$(git remote -v)" ]]; then
+			gh secret delete "$ENV" &> /dev/null
+		fi
+	done
+fi
+
+echo
+echo "# Setting keys"
+
+# set secrets to cloudflare
+echo "## Cloud flare"
 IFS="="
 while read -rs KEY VALUE; do
 	# sets secrets to worker automatically
 	if [ -n "$KEY" ]; then
-		echo "$VALUE" | yarn wrangler secret put "$KEY"
+		echo "- $KEY"
+		echo "$VALUE" | yarn wrangler secret put "$KEY" &> /dev/null
 	fi
 done <.dev.vars
 
+echo "## Github"
 # set secrets to github (if CLI is found)
 if command -v gh 1> /dev/null && [[ -n "$(git remote -v)" ]]; then
 	gh secret set -f .dev.vars
